:concurrency: 3
:queues:
  - default
  - mailers
  - newsletter
  - newsletters_opt_in
  - events
  - metrics
  - exports
  - translations
  - spam_analysis
  - user_report
  - reminders
  - close_meeting_reminder
  - vote_reminder
  - conference_diplomas
  - active_storage_analysis
  - active_storage_purge
